repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/aws-cloudformation/cfn-lint
    rev: v1.18.1
    hooks:
      - id: cfn-lint
        name: CloudFormation Linter
        description: Lint CloudFormation templates using cfn-lint
        entry: cfn-lint
        language: python
        types: [yaml, json]  # Specify the file types
        # files: ^templates/.*\.(yaml|yml|json)$  # Ensure it only checks files in the 'templates' folder
        files: templates/.*
